<?php // @codingStandardsIgnoreFile ?>
<?php $code = $this->getMethodCode() ?>

<div id="payment-errors" class="validation-advice" style="display:none;"></div>
<fieldset class="form-list buckaroo-method">
    <ul id="payment_form_<?php echo $code ?>" style="display:none" class="buckaroo3extended_input">
        <li>
            <label for="<?php echo $code;?>_BPE_Customergender" class="required">
                <?php echo $this->__('Salutation');?>: <em>*</em>
            </label>
            <div class="input-box">
                <select name="<?php echo $code;?>_BPE_Customergender" class="validate-select validate-number"
                        title="<?php echo $this->__('Salutation');?>" id="<?php echo $code;?>_BPE_Customergender">
                    <option value=''><?php echo $this->__('Select'); ?></option>
                    <option value="1" <?php echo (in_array($this->getGender(), array(1, 123))) ? 'selected' : '';?>>
                        <?php echo $this->__('Mr.'); ?>
                    </option>
                    <option value="2" <?php echo (in_array($this->getGender(), array(2, 124))) ? 'selected' : '';?>>
                        <?php echo $this->__('Mrs.'); ?>
                    </option>
                </select>
            </div>
        </li>
        <li>
            <label><?php echo $this->__('Billing name');?>:</label>
            <div class="input-box">
                <span class="disabled stylefix" id="<?php echo $code;?>_BPE_Customername"
                      title="<?php echo $this->__('Name');?>"><?php echo $this->escapeHtml($this->getName()); ?></span>
            </div>
        </li>
        <?php
        $telephone = $this->getAddress()->getTelephone();
        $display = ($telephone && $telephone != '-') ? 'style="display:none;"' : '';
        ?>
        <li <?php echo $display; ?>>
            <label class="required" for="<?php echo $code;?>_BPE_Customerphone">
                <?php echo $this->__('Telephone') ?>: <em>*</em>
            </label>
            <div class="input-box">
                <input class="input-text required-entry" type="text" title="<?php echo $this->__('Telephone') ?>"
                       name="<?php echo $code;?>_bpe_customer_phone_number"
                       value="<?php echo $this->escapeHtml($this->getPhoneNumber()); ?>"
                       id="<?php echo $code;?>_BPE_Customerphone"/>
            </div>
        </li>
        <li>
            <?php
            echo $this->getLayout()->createBlock('buckaroo3extended/customer_widget_dob')
                ->setFieldIdFormat($code . ':billing:%s')
                ->setFieldNameFormat('payment[' . $code . '][%s]')
                ->setIsRequired(true)
                ->setPaymentMethodCode($code)
                ->setDate($this->getDob())
                ->toHtml();
            ?>
        </li>

        <?php if($this->getPaymethod() == 'afterpayacceptgiro'):?>
            <li>
                <label for="<?php echo $code;?>_BPE_customer_account_number" class="required">
                    <?php echo $this->__('Bank account number') ?>: <em>*</em>
                </label>
                <div class="input-box">
                    <input class="input-text required-entry" type="text"
                           title="<?php echo $this->__('Bank account number') ?>"
                           name="<?php echo $code;?>_bpe_customer_account_number"
                           value="<?php echo $this->escapeHtml($this->getBankAccount()); ?>"
                           id="<?php echo $code;?>_BPE_customer_account_number" />
                </div>
            </li>
        <?php endif;?>


        <?php $currentBusiness = $this->getBusiness(); ?>

        <?php
        if ($this->getPaymethod() != 'afterpaydigiaccept' || $this->getBillingCountry() == 'BE') {
            $currentBusiness = '1';
        }
        ?>

        <?php if($currentBusiness == '1'): ?>
            <li>
                <input type="hidden" name="<?php echo $code;?>_BPE_BusinessSelect" value="1"
                       id="<?php echo $code;?>_BPE_BusinessSelect"/>
            </li>
        <?php elseif($currentBusiness == '2'):?>
            <li>
                <input type="hidden" name="<?php echo $code;?>_BPE_BusinessSelect" value="2"
                       id="<?php echo $code;?>_BPE_BusinessSelect"/>
                <div id="b2b-fields">
                    <label class="required" for="<?php echo $code;?>_BPE_CompanyCOCRegistration">
                        <?php echo $this->__('COC Number');?>
                    </label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text"
                               name="<?php echo $code;?>_BPE_CompanyCOCRegistration"
                               id="<?php echo $code;?>_BPE_CompanyCOCRegistration"
                               value="<?php echo $this->escapeHtml($this->getCompanyCOCRegistration());?>" />
                    </div>
                    <label class="required" for="<?php echo $code;?>_BPE_CompanyName">
                        <?php echo $this->__('Company Name');?>
                    </label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $code;?>_BPE_CompanyName"
                               id="<?php echo $code;?>_BPE_CompanyName"
                               value="<?php echo $this->escapeHtml($this->getCompanyName());?>" />
                    </div>
                </div>
            </li>
        <?php elseif($currentBusiness == '3'):?>
            <li>
                <label for="<?php echo $code;?>_BPE_BusinessSelect"><?php echo $this->__('Set Business');?>:</label>
                <div class="input-box">
                    <select name="<?php echo $code;?>_BPE_BusinessSelect" class="validate-select validate-number"
                            title="<?php echo $this->__('Set Business');?>" id="<?php echo $code;?>_BPE_BusinessSelect">
                        <option value="1" <?php echo (($this->getBusinessSelect()=='1')?'selected':'') ;?>>
                            <?php echo $this->__('B2C');?>
                        </option>
                        <option value="2" <?php echo (($this->getBusinessSelect()=='2')?'selected':'') ;?>>
                            <?php echo $this->__('B2B');?>
                        </option>
                    </select>
                </div>
                <?php
                $style = '';
                if (null === $this->getBusinessSelect() || $this->getBusinessSelect() == '1') {
                    $style = ' style="display:none;"';
                }
                ?>
                <div id="b2b-fields"<?php echo $style;?>>
                    <label class="required" for="<?php echo $code;?>_BPE_CompanyCOCRegistration">
                        <?php echo $this->__('COC Number');?>
                    </label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text"
                               name="<?php echo $code;?>_BPE_CompanyCOCRegistration"
                               id="<?php echo $code;?>_BPE_CompanyCOCRegistration"
                               value="<?php echo $this->escapeHtml($this->getCompanyCoCRegistration());?>" />
                    </div>
                    <label class="required" for="<?php echo $code;?>_BPE_CompanyName">
                        <?php echo $this->__('Company Name');?>
                    </label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $code;?>_BPE_CompanyName"
                               id="<?php echo $code;?>_BPE_CompanyName"
                               value="<?php echo $this->escapeHtml($this->getCompanyName());?>" />
                    </div>
                </div>
            </li>
        <?php endif; ?>

        <li class="tac-accept">
            <div class="input-box">
                <input class="input-checkbox required-entry" type="checkbox"
                       title="<?php echo $this->__('Terms and Conditions') ?>"
                       name="<?php echo $code;?>_bpe_accept" value="checked"
                       id="<?php echo $code;?>_BPE_terms_and_conditions" />
            </div>
            <label for="<?php echo $code;?>_BPE_terms_and_conditions" class="required">
                <?php echo $this->__(
                    'Yes, I accept the %sterms and condition%s for the use of Afterpay.',
                    '<a style="float:none;margin:0;" id="' . $code . '-tos-url" target="_blank" href="' .
                    $this->getTosUrl() . '">',
                    '</a>'
                ) ?> <em>*</em>
            </label>
        </li>

        <li>
            <?php echo Mage::helper('buckaroo3extended')
                ->__('Please make sure all fields are filled in correctly before proceeding.')?>
        </li>
    </ul>
</fieldset>
<script type="text/javascript">
    var paymentCode = '<?php echo $code;?>';

    $(paymentCode + '_BPE_BusinessSelect').observe('change', function(event){
        if($(paymentCode + '_BPE_BusinessSelect').getValue() == 2){
            $('b2b-fields').show();
            var b2bUrl = '<?php echo $this->getB2BUrl(); ?>';
            $('<?php echo $code; ?>-tos-url').href =  b2bUrl;
        }

        if($(paymentCode + '_BPE_BusinessSelect').getValue() == 1){
            $('b2b-fields').hide();
            var b2cUrl = '<?php echo $this->getB2CUrl(); ?>';
            $('<?php echo $code; ?>-tos-url').href = b2cUrl;
        }
    });
</script>

