<?php // @codingStandardsIgnoreFile ?>
<?php $code=$this->getMethodCode() ?>

<div id="payment-errors" class="validation-advice" style="display:none;"></div>
<fieldset class="form-list buckaroo-method">
    <ul id="payment_form_<?php echo $code ?>" style="display:none" class="buckaroo3extended_input">
        <li>
            <label for="<?php echo $code;?>_BPE_Customergender" class="required">
                <?php echo $this->__('Salutation');?>: <em>*</em>
            </label>
            <div class="input-box">
                <select name="<?php echo $code;?>_BPE_Customergender" class="validate-select validate-number"
                        title="<?php echo $this->__('Salutation');?>" id="<?php echo $code;?>_BPE_Customergender">
                    <option value=''><?php echo $this->__('Select'); ?></option>
                    <option value="1" <?php echo (in_array($this->getGender(), array(1, 123))) ? 'selected' : '';?>>
                        <?php echo $this->__('Mr.'); ?>
                    </option>
                    <option value="2" <?php echo (in_array($this->getGender(), array(2, 124))) ? 'selected' : '';?>>
                        <?php echo $this->__('Mrs.'); ?>
                    </option>
                </select>
            </div>
        </li>
        <li>
            <label><?php echo $this->__('Billing name');?>:</label>
            <div class="input-box">
                <span class="disabled" id="<?php echo $code;?>_BPE_Customername"
                      title="<?php echo $this->__('Name');?>">
                    <?php echo $this->escapeHtml($this->getName()); ?>
                </span>
            </div>
        </li>
        <?php
        $telephone = $this->getAddress()->getTelephone();
        $display = ($telephone && $telephone != '-') ? 'style="display:none;"' : '';
        ?>
        <li <?php echo $display; ?>>
            <label class="required" for="<?php echo $code;?>_BPE_Customerphone">
                <?php echo $this->__('Telephone') ?>: <em>*</em>
            </label>
            <div class="input-box">
                <input class="input-text required-entry" type="text" title="<?php echo $this->__('Telephone') ?>"
                       name="<?php echo $code;?>_bpe_customer_phone_number"
                       value="<?php echo $this->escapeHtml($this->getPhoneNumber()); ?>"
                       id="<?php echo $code;?>_BPE_Customerphone"/>
            </div>
        </li>
        <li>
            <?php
            echo $this->getLayout()
                ->createBlock('buckaroo3extended/customer_widget_dob')
                ->setFieldIdFormat($code . ':billing:%s')
                ->setFieldNameFormat('payment[' . $code . '][%s]')
                ->setIsRequired(true)
                ->setPaymentMethodCode($code)
                ->setDate($this->getDob())
                ->toHtml();
            ?>
        </li>
        <li>
            <label for="<?php echo $code;?>_BPE_customer_account_number" class="required">
                <?php echo $this->__('Bank account number') ?>: <em>*</em>
            </label>
            <div class="input-box">
                <input class="input-text required-entry validate-buckaroo-iban" type="text"
                       title="<?php echo $this->__('Bank account number') ?>"
                       name="<?php echo $code;?>_bpe_customer_account_number"
                       value="<?php echo $this->escapeHtml($this->getBankAccount()); ?>"
                       id="<?php echo $code;?>_BPE_customer_account_number" />
            </div>
        </li>
        <li class="tac-accept">
            <div class="input-box">
                <input class="input-checkbox required-entry" type="checkbox"
                       title="<?php echo $this->__('Terms and Conditions') ?>"
                       name="<?php echo $code;?>_bpe_terms_and_conditions" value="checked"
                       id="<?php echo $code;?>_BPE_terms_and_conditions" />
            </div>
            <label for="<?php echo $code;?>_BPE_terms_and_conditions" class="required">
                <?php echo $this->__(
                    'Yes, I accept the %sterms and condition%s for the use of Payment Guarantee.',
                    '<a href="#" id="paymentguarantee_terms_and_conditions_link">', '</a>'
                ) ?> <em>*</em>
            </label>
        </li>
        <li>
            <?php echo Mage::helper('buckaroo3extended')
                ->__('Please make sure all fields are filled in correctly before proceeding.')?>
        </li>
    </ul>
</fieldset>
<?php echo $this->getLayout()->createBlock('core/template')
    ->setTemplate('buckaroo3extended/paymentguarantee/termsAndConditions.phtml')->toHtml();?>
