<?php // @codingStandardsIgnoreFile ?>
<?php $code=$this->getMethodCode() ?>
<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<ul id="payment_form_<?php echo $code ?>" style="display:none" class="buckaroo3extended_input">
    <li>
        <div class="input-box">
            <label for="<?php echo $code;?>_BPE_Customergender"><?php echo $this->__('Salutation') ?></label>
            <br>
            <select name="<?php echo $code;?>_BPE_Customergender"
                    class="validate-select"
                    id="<?php echo $code;?>_BPE_Customergender">
                <option value="1" <?php echo ($this->getGender() === 1) ? 'selected' : '';?>>
                    <?php echo $this->__('Mr.'); ?>
                </option>
                <option value="2" <?php echo ($this->getGender() === 2) ? 'selected' : '';?>>
                    <?php echo $this->__('Mrs.'); ?>
                </option>
            </select>
        </div>
    </li>
    
    <li>
        <div class="input-box">
            <label for="<?php echo $code;?>_BPE_Customerfirstname">
                <?php echo $this->__('First Name') ?> <span class="required">*</span>
            </label>
            <br>
            <input class="input-text required-entry f-name"
                   type="input"
                   name="<?php echo $code;?>_BPE_Customerfirstname"
                   value="<?php echo $this->getFirstname(); ?>"
                   id="<?php echo $code;?>_BPE_Customerfirstname" />
        </div>
    </li>
    
    <li>
        <div class="input-box">
            <label for="<?php echo $code;?>_BPE_Customerlastname">
                <?php echo $this->__('Last Name') ?> <span class="required">*</span>
            </label>
            <br>
            <input class="input-text required-entry l-name"
                   type="input"
                   name="<?php echo $code;?>_BPE_Customerlastname"
                   value="<?php echo $this->getLastname(); ?>"
                   id="<?php echo $code;?>_BPE_Customerlastname" />
        </div>
    </li>
    
    <li>
        <div class="input-box">
            <label for="<?php echo $code;?>_BPE_Customermail">
                <?php echo $this->__('E-mail') ?> <span class="required">*</span>
            </label>
            <br>
            <input class="input-text required-entry validate-email"
                   type="input"
                   name="<?php echo $code;?>_BPE_Customermail"
                   value="<?php echo $this->getEmail(); ?>"
                   id="<?php echo $code;?>_BPE_Customermail" />
        </div>
    </li>
    
    <li>
        <?php echo $this->__(
            'You will receive an email with further payment instructions when you place your order.'
        ) ?>
    </li>
</ul>
