<?php // @codingStandardsIgnoreFile ?>
<div class="module-message buckaroo">
    <h4>
        <?php echo Mage::helper('buckaroo3extended')->__(
                'Looking for Buckaroo payment methods? We have our own tab to the left under Sales.'
        )?>
    </h4>
</div>
<?php /* Stylesheet not available */ ?>
<style>
    .module-message { padding:9px 9px 9px 30px; margin-bottom:20px; border:1px solid #ccc; }
    .module-message.buckaroo { margin-bottom:25px; background:url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>adminhtml/default/default/images/tig_buckaroo3extended/buckaroo_small.png) 9px 12px no-repeat; padding:9px 9px 9px 92px; }
    .module-message.buckaroo h4 { margin:0; }
</style>
