<div id="payment-errors" class="validation-advice" style="display:none;"></div>
<?php // @codingStandardsIgnoreFile ?>
<?php $code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $code; ?>" style="display:none;"
    class="buckaroo3extended_input  form-list buckaroo-method">
    <li>
        <label for="<?php echo $code ?>_account_owner" class="required">
            <?php echo $this->__('Bank account holder') ?>:<em>*</em>
        </label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Bank account holder') ?>" class="input-text required-entry"
                   id="<?php echo $code ?>_account_owner" name="payment[account_owner]"
                   value="<?php echo $this->escapeHtml($this->getAccountOwner()); ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $code ?>_account_number" class="required">
            <?php echo $this->__('Bank account number') ?>:<em>*</em>
        </label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Bank account number') ?>"
                   class="input-text required-entry validate-buckaroo-iban" id="<?php echo $code ?>_account_number"
                   name="payment[account_number]" value="<?php echo $this->escapeHtml($this->getAccountNumber()); ?>" />
        </div>
    </li>
    <?php if($this->getBillingCountry() != 'NL'):?>
        <li>
            <label for="<?php echo $code ?>_bank_number"><?php echo $this->__('BIC number') ?>:</label>
            <div class="input-box">
                <input type="text" title="<?php echo Mage::helper('buckaroo3extended')->__('BIC number') ?>"
                       class="input-text" id="<?php echo $code ?>_bank_number" name="payment[bank_number]"
                       value="<?php echo $this->escapeHtml($this->getBankNumber()); ?>" />
            </div>
        </li>
    <?php else:?>
        <input type="hidden" id="<?php echo $code ?>_bank_number" name="payment[bank_number]" value="" />
    <?php endif;?>
    <li>
        <?php
        echo Mage::helper('buckaroo3extended')->__("Please enter these fields as they appear on your bank account.");
        ?>
    </li>
</ul>
