<?php
// @codingStandardsIgnoreLine
class TIG_Buckaroo3Extended_Block_PaymentMethods_Idealprocessing_Adminhtml_System_Config_Advancedbtn
    extends TIG_Buckaroo3Extended_Block_PaymentMethods_Ideal_Adminhtml_System_Config_Advancedbtn
{

}
