<?php
// @codingStandardsIgnoreLine
class Buckaroo_Buckaroo3Extended_Block_PaymentMethods_Afterpay2_Adminhtml_System_Config_Advancedbtn
      extends Buckaroo_Buckaroo3Extended_Block_PaymentMethods_Afterpay_Adminhtml_System_Config_Advancedbtn
{

}
