<?php // @codingStandardsIgnoreFile ?>
<div style="
background-image:url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>adminhtml/default/default/images/fam_bullet_error.gif');
background-repeat:no-repeat; 
background-color:rgb(255,255,255); 
padding:9px;
padding-left:28px;
height:27px;
border:1px solid #CCCCCC;
background-position:10px 10px;
">
    <h4>
        <?php echo Mage::helper('buckaroo3extended')->__(
            'Options for Buckaroo 3 Extended Refunding are only available at the Default Config (GLOBAL) level.'
        );?>
    </h4>
</div>
