<![if !lt IE 9]>
<script type="text/javascript">
function sendData(element)
{
    jQuery_1123.post(
        <?php // @codingStandardsIgnoreLine ?>
         '<?php echo Mage::getUrl('buckaroo3extended/checkout/saveData', array('_secure'=>true)); ?>',
         {
             name: element.attr('name'),
             value: element.val()
         }
     );
}
</script>
<?php $skinUrl = $this->getSkinUrl('js/TIG/Buckaroo3Extended/saveData.js', array('_secure' => true)); ?>
<?php // @codingStandardsIgnoreLine ?>
<script type="text/javascript" src="<?php echo $skinUrl; ?>"></script>
<![endif]>

<script type="text/javascript">
document.observe('dom:loaded', function(){

    function isValidIBAN($v){ //This function check if the checksum if correct
        $v = $v.replace(/^(.{4})(.*)$/,"$2$1"); //Move the first 4 chars from left to the right
        $v = $v.replace(/[A-Z]/g,function($e){return $e.charCodeAt(0) - 'A'.charCodeAt(0) + 10}); //Convert A-Z to 10-25
        var $sum = 0;
        var $ei = 1; //First exponent
        for(var $i = $v.length - 1; $i >= 0; $i--){
            $sum += $ei * parseInt($v.charAt($i),10); //multiply the digit by it's exponent
            $ei = ($ei * 10) % 97; //compute next base 10 exponent  in modulus 97
        };
        return $sum % 97 == 1;
    }

    Validation.add(
        'validate-buckaroo-iban',
        <?php // @codingStandardsIgnoreLine ?>
        '<?php echo Mage::helper('buckaroo3extended')->__('Please enter a valid IBAN.'); ?>',
        function(value){
            var pattern = new RegExp('^[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{4}[0-9]{7}([a-zA-Z0-9]?){0,16}$');
            return (pattern.test(value) && isValidIBAN(value));
        }
    );

});
</script>
